models:
- columns:
  - description: A numeric identifier uniquely identifying each currency within the
      table.
    name: CURRENCYKEY
    tests:
    - unique
    - not_null
  - description: An alternate key or code representing the currency, often aligned
      with international currency codes for easy reference.
    name: CURRENCYALTERNATEKEY
  - description: The full name of the currency, providing clear identification for
      reporting and transaction purposes.
    name: CURRENCYNAME
  description: Stores information about various currencies used in transactions, including
    their names and unique identifiers, to support financial operations and reporting
    across different currencies!!!!!
  name: DIMCURRENCY
- columns:
  - name: SALESTERRITORYKEY
    tests:
    - unique
    - not_null
  - description: null
    name: SALESTERRITORYALTERNATEKEY
  - description: null
    name: SALESTERRITORYGROUP
  - description: null
    name: SALESTERRITORYREGION
  - description: null
    name: SALESTERRITORYCOUNTRY
  description: null
  name: DIMSALESTERRITORY
version: 2
