version: 2

models:
  - name: DIMCURRENCY
    description:

    columns:
      - name: CURRENCYKEY
        tests:
          - unique
          - not_null

      - name: CURRENCYALTERNATEKEY
        description:

      - name: CURRENCYNAME
        description:

  - name: DIMSALESTERRITORY
    description:

    columns:
      - name: SALESTERRITORYKEY
        tests:
          - unique
          - not_null

      - name: SALESTERRITORYALTERNATEKEY
        description:

      - name: SALESTERRITORYGROUP
        description:

      - name: SALESTERRITORYREGION
        description:

      - name: SALESTERRITORYCOUNTRY
        description:
